### ISSUE TITLE
Make matplotlib optional

### ISSUE THREAD

**Issue by cdeil** [giacomov/3ML#11]
I'm getting this error when I try to import `threeML`.

In Astropy and Gammapy we put the `matplotlib.pyplot` import inside the function or methods that need it, so that matplotlib is an optional dependency.

Can you do the same for threeML?

```
$ python
Python 2.7.8 (default, Aug 20 2015, 11:36:15) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import UnbinnedAnalysis
Plotter is MatPlotlib
>>> import threeML
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "threeML/__init__.py", line 53, in <module>
    from .models.spectralmodel import *
  File "threeML/models/spectralmodel.py", line 11, in <module>
    import matplotlib.pyplot as plt
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
>>> import matplotlib
>>> import threeML
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "threeML/__init__.py", line 53, in <module>
    from .models.spectralmodel import *
  File "threeML/models/spectralmodel.py", line 11, in <module>
    import matplotlib.pyplot as plt
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/deil/software/fermi/latest/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

**Comment by grburgess** [comment]
@cdeil is this still an issue? @giacomov do we want to change this?

**Comment by giacomov** [comment]
With the new conda installation this should not be an issue anymore. We depend on matplotlib for many things, so while making it an optional dependency is feasible, it would be difficult.

**Comment by cdeil** [comment]
> @cdeil is this still an issue?

I don't know.

If it's not the case already, would still suggest to only import MPL when needed, at least the interactive MPL stuff that happens when you `import matplotlib.pyplot`.
