### ISSUE TITLE
crash writing fit results with only unitless free parameters to fits file

### ISSUE THREAD

**Issue by henrikef** [giacomov/3ML#287]
Hi!

I have been unable to write some fit results to fits files. I think I tracked it down to models where all of the free parameters are unitless. In my case, I was trying to fit a model where the ratio of the flux normalization between sources is fixed and there's only one free parameter to scale all of the fluxes, which is unitless.

In any case, here's an example that crashes for me:

```
import numpy as np
import healpy as hp
import warnings

with warnings.catch_warnings():

    warnings.simplefilter("ignore")
    
    from threeML import *

fluxUnit = 1. / (u.TeV * u.cm**2 * u.s)

spectrum=Powerlaw()* Constant() 
source = PointSource( "tst", ra=100 , dec=20, spectral_shape=spectrum)
model = Model(source)

spectrum.piv_1 = 7*u.TeV      
spectrum.index_1 = -2.3
spectrum.K_1 = 1e-15*fluxUnit      
spectrum.k_2 = 0.1

#three free parameters (one with units): works
spectrum.piv_1.fix = True
cov_matrix = np.diag([0.001]*3)
results = analysis_results.MLEResults(model, cov_matrix, {})  
results.write_to("test1.fits")

#one free parameter with units: works
spectrum.index_1.fix = True
spectrum.k_2.fix=True
cov_matrix = np.diag([0.001]*1)
results = analysis_results.MLEResults(model, cov_matrix, {})  
results.write_to("test2.fits")

#one free parameter without units: crashes
spectrum.index_1.fix = False
spectrum.K_1.fix=True
cov_matrix = np.diag([0.001]*1)
results = analysis_results.MLEResults(model, cov_matrix, {})  
results.write_to("test3.fits")

#two free parameter with units: crashes
spectrum.k_2.fix=False
cov_matrix = np.diag([0.001]*2)
results = analysis_results.MLEResults(model, cov_matrix, {})  
results.write_to("test4.fits")
```

with the following warnings/errors:

```
INFO [LoadProject.cc, load_project:69]: liff loaded
WARNING: AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead. [astropy.utils.decorators]
WARNING:astropy:AstropyDeprecationWarning: "clobber" was deprecated in version 2.0 and will be removed in a future version. Use argument "overwrite" instead.

WARNING UserWarning: Field 5 has a repeat count of 0 in its format code, indicating an empty field.

Traceback (most recent call last):
  File "breakFits.py", line 40, in <module>
    results.write_to("test3.fits")
  File "/Users/hfleisch/software/miniconda2/envs/sciencetools_hawc/lib/python2.7/site-packages/threeML/analysis_results.py", line 418, in write_to
    fits_file.writeto(sanitize_filename(filename), overwrite=overwrite)
  File "/Users/hfleisch/software/miniconda2/envs/sciencetools_hawc/lib/python2.7/site-packages/threeML/io/fits_file.py", line 88, in writeto
    self._hdu_list.writeto(*args, **kwargs)
  File "/Users/hfleisch/software/miniconda2/envs/sciencetools_hawc/lib/python2.7/site-packages/astropy/utils/decorators.py", line 507, in wrapper
    return function(*args, **kwargs)
  File "/Users/hfleisch/software/miniconda2/envs/sciencetools_hawc/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 888, in writeto
    hdu._prewriteto(checksum=checksum)
  File "/Users/hfleisch/software/miniconda2/envs/sciencetools_hawc/lib/python2.7/site-packages/astropy/io/fits/hdu/table.py", line 452, in _prewriteto
    update_heap_pointers=not self._manages_own_heap)
  File "/Users/hfleisch/software/miniconda2/envs/sciencetools_hawc/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 1137, in _scale_back
    self._scale_back_strings(indx, dummy, raw_field)
  File "/Users/hfleisch/software/miniconda2/envs/sciencetools_hawc/lib/python2.7/site-packages/astropy/io/fits/fitsrec.py", line 1202, in _scale_back_strings
    input_field = input_field.flatten().view(output_field.dtype)
ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype
```

**Comment by giacomov** [comment]
Thanks for spotting this and for providing a minimal working example, that was very useful to track down the bug.

I have solved it now, if you are using the `conda` distribution you can do `conda install -c conda-forge -c threeml threeml` as soon as this Travis build has completed:

https://travis-ci.org/giacomov/3ML/jobs/359050791

If you are using a development version installed with `pip`, you can `git pull` and install right now.

Let me know if you have further issues, if not please close the issue as soon as you verify it works.

**Comment by henrikef** [comment]
Thanks! Working so far 👍 !
