### ISSUE TITLE
io module in 3ML may clash with system io module

### ISSUE THREAD

**Issue by sybenzvi** [giacomov/3ML#4]
On OS X Yosemite I can build 3ML and import it in ipython sessions, but oddly "import threeML" fails when running a plain python session.  I copy my error below.  After googling around it seems there is a possibility this error is caused by the fact that threeML contains an io directory which may be clashing with another io package in the system python; see comments here:

http://stackoverflow.com/questions/6315440/how-to-solve-attributeerror-when-importing-igraph

The recommended fix is to rename this directory -- io3ML is a suggestion.  My error messages are copied below.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/threeML-0.1.0-py2.7-macosx-10.10-intel.egg/threeML/__init__.py", line 46, in <module>
    from .models.PointSource import PointSource
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/threeML-0.1.0-py2.7-macosx-10.10-intel.egg/threeML/models/PointSource.py", line 1, in <module>
    from SourceModel import SourceModel
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/threeML-0.1.0-py2.7-macosx-10.10-intel.egg/threeML/models/SourceModel.py", line 4, in <module>
    from threeML.io.Table import Table
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/threeML-0.1.0-py2.7-macosx-10.10-intel.egg/threeML/io/Table.py", line 6, in <module>
    import astropy.table
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/astropy-1.0.3-py2.7-macosx-10.10-intel.egg/astropy/__init__.py", line 73, in <module>
    _check_numpy()
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/astropy-1.0.3-py2.7-macosx-10.10-intel.egg/astropy/__init__.py", line 61, in _check_numpy
    from .utils import minversion
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/astropy-1.0.3-py2.7-macosx-10.10-intel.egg/astropy/utils/__init__.py", line 20, in <module>
    from .compat.odict import OrderedDict
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/astropy-1.0.3-py2.7-macosx-10.10-intel.egg/astropy/utils/compat/__init__.py", line 14, in <module>
    from .numpycompat import *
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/astropy-1.0.3-py2.7-macosx-10.10-intel.egg/astropy/utils/compat/numpycompat.py", line 18, in <module>
    NUMPY_LT_1_6_1 = not minversion('numpy', '1.6.1')
  File "/Users/sybenzvi/Library/Python/2.7/lib/python/site-packages/astropy-1.0.3-py2.7-macosx-10.10-intel.egg/astropy/utils/introspection.py", line 143, in minversion
    from pkg_resources import parse_version
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 25, in <module>
    # Since we may exit via an exception, close fp explicitly.
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 501, in <module>
    class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'

**Comment by giacomov** [comment]
Thanks for reporting this.

Changing a module name is not a long term solution, because someone else might one day write one with a similar name.

I investigated and found that the problem can be avoided by simply reordering things in the __init__.py file under threeML.

I am going to commit and fix this.

**Comment by sybenzvi** [comment]
Thanks, this fixes it for me too.
